### ISSUE TITLE
TypeError: Object #<Object> has no method 'onTest'

### ISSUE THREAD

**Issue by aldeed** [raix/docmeteor#14]
Getting this error when running `docmeteor` command for autoform. This is on a computer where I just installed docmeteor for the first time.

```
Package.js found, parsing...

/Users/eric/.codepackage.js:226
Package.onTest(function (api) {
        ^
TypeError: Object #<Object> has no method 'onTest'
    at Object.<anonymous> (/Users/eric/.codepackage.js:226:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/docmeteor/meteor-js-doc.js:44:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by aldeed** [comment]
Figured it out. See PR #15
